### PR TITLE
Black hair improvements finished

### PR DESCRIPTION
**Pull request by orbitllc**
Get your wig!! Got this thing detecting my black cat on the ground at this point. Really clean with very descriptive logging

**TODO:** Fix comments

NOTE: I have some thoughts about installation for wide doors.

### CODE REVIEW

**Comment by chipmc** [comment]
Merged

**Comment by chipmc** [comment]
@orbitllc , 

Question about your handling of SPADS for the two modes - detection and occupancy.  Could you explain what the two areas are?  Based on your comments it sounds like you have figured out a way not to change SPAD detection zones when changing between modes, is this right?

**Comment by orbitllc** [comment]
Correct, I have it set up so the detection zone is a single 16x16 spad
array that is centered at the center of the array.

The occupancy zones are 4x4s that are centered at the center of each side

**Comment by orbitllc** [comment]
I might have misunderstood, the way it works is that the single 16x16
triggers occupancy mode, which are the smaller zones, then it will count
until it goes back to zero then recalibrate all 3 zones and sleep

**Pull request merged**
